name: Maven Release

# Performs a Maven release using JDK 11 when a new GitHub release has been published
on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Maven Artifact Publisher (JDK 11)
    runs-on: ubuntu-latest
    env:
      AUTORELEASE_ARTIFACT: ${{ secrets.AUTORELEASE_ARTIFACT }}
      SKIP_JAR_DEPLOYMENT: ${{ secrets.SKIP_JAR_DEPLOYMENT }}
      FREELIBRARY_CACHE_KEY: ${{ secrets.FREELIBRARY_CACHE_KEY }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Install JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # If running locally in act, install Maven
      - name: Set up Maven if needed
        if: ${{ env.ACT }}
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Set up Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: freelibrary-cache-${{ env.FREELIBRARY_CACHE_KEY }}
      - name: Set autorelease config
        if: env.AUTORELEASE_ARTIFACT == null
        run: echo "AUTORELEASE_ARTIFACT=false" >> $GITHUB_ENV
      - name: Set Jar deployment config
        if: env.SKIP_JAR_DEPLOYMENT == null
        run: echo "SKIP_JAR_DEPLOYMENT=false" >> $GITHUB_ENV
      - name: Release with Maven
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          gpg_private_key: ${{ secrets.BUILD_KEY }}
          gpg_passphrase: ${{ secrets.BUILD_PASSPHRASE }}
          nexus_username: ${{ secrets.SONATYPE_USERNAME }}
          nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
          maven_profiles: "release"
          maven_args: >
            -Drevision=${{ github.event.release.tag_name }} -DautoReleaseAfterClose=${{ env.AUTORELEASE_ARTIFACT }}
            -ntp -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error
            -DskipNexusStagingDeployMojo=${{ env.SKIP_JAR_DEPLOYMENT }}
            -Ddocker.registry.username=${{ secrets.DOCKER_USERNAME }}
            -Ddocker.registry.account=${{ secrets.DOCKER_REGISTRY_ACCOUNT}}
            -Ddocker.registry.password=${{ secrets.DOCKER_PASSWORD }}
