#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TAG="$($DIR/next_tag)"

echo "Preparing $($DIR/get_version)"

$DIR/version

git commit -am "Creating new version: $($DIR/get_version)"
git push

$DIR/tag "$TAG"
$DIR/push_tag
