name: Dependabot Auto-Merge

on:
  pull_request:
    branches:
      - main
jobs:
  merge:
    name: Dependabot Updater
    runs-on: ubuntu-latest
    steps:
      -  name: Check out code
         uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2
      -  name: Merge Dependabot PR
         uses: ahmadnassri/action-dependabot-auto-merge@5333af2ca11b4ab5c65070b0fa80aef083d87c5b # v2.3.0
         with:
           config: .github/configs/dependabot-auto-merge.yml
           github-token: ${{ secrets.ACTIONS_PAT }}
