name: Draft Release

# Any time new commits hit the 'main' branch, add them to the next release draft
on:
  push:
    branches:
      - main

jobs:
  draft-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        with:
          config-name: configs/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
