name: Draft Release

# Any time new commits hit the 'main' branch, add them to the next release draft
on:
  push:
    branches:
      - main

jobs:
  draft-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
        with:
          config-name: configs/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
