name: Draft Release

# Any time new commits hit the 'main' branch, add them to the next release draft
on:
  push:
    branches:
      - main

jobs:
  draft-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@ed4bc48ec97379be2258e7b7ac2624a3e26ab809 # v7.4.0
        with:
          config-name: configs/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
